# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Building amqp
      run: |
        mvn -B package --file amqp/pom.xml -DskipTests
    - name: Building java8
      run: |    
        mvn -B package --file java8/pom.xml -DskipTests
    - name: Building java8-hibernate-reactive
      run: |      
        mvn -B package --file java8-hibernate-reactive/pom.xml -DskipTests
    - name: Building mutiny
      run: |     
        mvn -B package --file mutiny/pom.xml -DskipTests
    - name: Building mutiny-hibernate-reactive
      run: |     
        mvn -B package --file mutiny-hibernate-reactive/pom.xml -DskipTests
    - name: Building post-service
      run: |     
        mvn -B package --file post-service/pom.xml -DskipTests
    - name: Building restclient
      run: |     
        mvn -B package --file restclient/pom.xml -DskipTests
    - name: Building restclient-java11
      run: |     
        mvn -B package --file restclient-java11/pom.xml -DskipTests
    - name: Building restclient-jaxrs
      run: |     
        mvn -B package --file restclient-jaxrs/pom.xml -DskipTests
    - name: Building restclient-vertx-mutiny
      run: |     
        mvn -B package --file restclient-vertx-mutiny/pom.xml -DskipTests
    - name: Building resteasy-reactive
      run: |     
        mvn -B package --file resteasy-reactive/pom.xml -DskipTests
    - name: Building rxjava2
      run: |     
        mvn -B package --file rxjava2/pom.xml -DskipTests
    - name: Building spring
      run: |     
        mvn -B package --file spring/pom.xml -DskipTests
    - name: Building vertx-routes
      run: |     
        mvn -B package --file vertx-routes/pom.xml -DskipTests
    - name: Building vertx-routes-mutiny
      run: |     
        mvn -B package --file vertx-routes-mutiny/pom.xml -DskipTests
    - name: Building restclient-kotlin
      run: |     
        //kotlin restclient using Gradle
        cd restclient-kotlin
        chomod a+x ./gradlew
        ./gradlew build -x test 
        
        
        
        
